### ISSUE TITLE
Run `test_while_loop` with a generated model

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#30]
See #23 

Test_while_loop adds an input and overrides an existing equation

- [x] Parse model inputs --> Get info down to model generation stage in FC
  - [x] Update code generation with inputs in CG
- [x] Parse equation --> Store equation somehow in ~CG~ FC
  - [x] Convert to sympy and resolve variable references (requires cellmlmanip model object)
  - [x] Raise (friendly) error if references can't be resolved
  - [x] Check if equation uses FC parts that don't fit in sympy?? (e.g. arrays)
  - [x] Update model with new equation

**Comment by MichaelClerx** [comment]
@jonc125 is that the logic you'd expect above?
Not sure how to get the equation info at the moment. Would mean either having some intermediate (unresolved) equation coming back from CompactSyntaxParser or passing the model (or a dict of name:dummy pairs) into the parser

**Comment by jonc125** [comment]
Some points:
* You shouldn't interact with CG until all the manipulation (add input, change equation) is done in cellmlmanip. So modify the model, *then* generate code.
* Equations in the model interface section can't use FC-specific constructs, only things allowed in CellML (except for the magic 'interpolate on a data file' construct, which is in a later test case).
* Not sure on the easiest approach to parsing. Would Sympy be able to parse the raw equation string? The challenge there would be keeping the units on numbers (and possibly recognising prefix:term style variable names). Or use the existing parse tree from pyparsing and have a mapping from that to Sympy terms?
* Name references would need to be resolved at this parsing stage so you get the correct VariableDummy. Which is why you handle input/output/var declarations before equations, so all symbols you need have been created. A dict of name:dummy pairs isn't quite what you need, because (most) of the name references in the protocol are to annotations (except for purely local-to-protocol declared variables).

**Comment by MichaelClerx** [comment]
> You shouldn't interact with CG until all the manipulation (add input, change equation) is done in cellmlmanip. So modify the model, then generate code.

Woops, meant to write FC there!

> Equations in the model interface section can't use FC-specific constructs, only things allowed in CellML (except for the magic 'interpolate on a data file' construct, which is in a later test case).

Is this handled by the CompactSyntaxParser?

**Comment by MichaelClerx** [comment]
Is it what this is for?
https://github.com/ModellingWebLab/weblab-fc/blob/master/fc/parsing/CompactSyntaxParser.py#L1143

**Comment by MichaelClerx** [comment]
But looks like the easiest way would be to write some code that converts the pyparsing tree to a sympy equation? Instead of passing a model to the parser somehow?

**Comment by jonc125** [comment]
But when you're processing the model interface, you need a `Model` to apply it to...?

**Comment by MichaelClerx** [comment]
That's right, but the current code is something like

```
proto = parse_protocol()
model = parse_model()
update_model_based_on_protocol(model, proto)
```

and I'm fairly sure that's how WL1 worked as well. But if we want the parser to create nice sympy objects we need something like

```
model = parse_model()
proto = parse_protocol(model)
update_model_based_on_protocol(model, proto)
```

**Comment by jonc125** [comment]
Yeah, (1) is tidier. In WL1 the model interface part of the protocol was basically ignored until the `update_model_based_on_protocol` bit though! So I was thinking that probably `parse_protocol` would just store the parse tree info (things like input declarations can be the mini objects that are the parse actions, equations can be the parser's tree) and then `update_model_based_on_protocol` can convert to sympy and resolve names at the same time - rather than having to create extra dummies when parsing the protocol and replacing them later?

**Comment by jonc125** [comment]
Turns out #93 finishes this issue too. We haven't done inputs 'properly', in that parameters & conversions etc aren't handled, but the case of a state variable input that's already in the model works, which is all that this protocol needs.
